### PR TITLE
Add ability to add paging to tags

### PR DESCRIPTION
**Pull request by hswolff**
Hello!

This adds the ability to add paging to a tag page.  I got a lot of inspiration for the paging code from [metalsmith-collections-paginate](https://github.com/blakeembrey/metalsmith-collections-paginate).

Let me know if this is a welcome change and what else you'd like to see updated so this can get merged upstream.

My paging looks like this for an example: 
image

Thanks!

### CODE REVIEW

**Comment by ben-eb** [comment]
Any updates on this?

**Comment by totocaster** [comment]
I've updated README with announcement. I'm looking for developer/maintainer for this project. Ping me if interested. Thanks, sorry for long wait.

**Comment by hswolff** [comment]
Hey @totocaster I'd be happy to maintain this project as I'm actively using it for my blog. Let me know!

**Comment by totocaster** [comment]
@hswolff Just, added as collaborator. Let me know if you have questions, concerns, anything. Thanks! I appreciate your time and initiative.

**Comment by hswolff** [comment]
thanks @totocaster!  could you also add me as a maintainer for the npm package?

I think the command is `npm owner add hswolff metalsmith-tags`

**Comment by totocaster** [comment]
Done. Thanks for your work.

**Pull request merged**
