### PR TITLE
added count property to tag list

### PR DESCRIPTION
**Pull request by tunix**

### CODE REVIEW

**Comment by hswolff** [comment]
Any reason you can't just use `[tag].length` directly?

**Comment by tunix** [comment]
@hswolff - typeof reported that it was an object rather than array. I didn't know arrays could have attributes like objects do. It isn't that obvious imho. `[tag].length` works.

**Comment by hswolff** [comment]
Yeah I'm hesitant to accept this merge as I prefer not to have two ways to do the same thing. I agree it's not well documented but that can be fixed with documentation and not by modifying code.  Inclined to close this without merging.

**Comment by tunix** [comment]
@hswolff no problem. closing it.

**Pull request closed without merging**
