### PR TITLE
Added normalize option

### PR DESCRIPTION
**Pull request by saschazar21**
This fixes issue #48.
Added an option to 'normalize' tags and exchange special characters like *äøßç* to their ASCII equivalents *aossc*.

This makes use of the *safeTag()* function and therefore depends on the value added to the *slug* property in the options object. However, for the standard *RFC 3986* mentioned in the README, it should be a good fit.

### CODE REVIEW

**Comment by jarodtaylor** [comment]
@hswolff this PR looks good to go, but before merging I wasn't sure if you had some guidelines (e.g. bumping version numbers, etc.)

**Comment by hswolff** [comment]
Typically I follow the rule of "what's easiest for the contributor, and what's easiest for the maintainer". i.e. I ask what is required of the contributor for the PR to complete the work described and to not introduce any regressions (in code, style, etc), and from there I'm happy to do any other book-keeping that needs doing, i.e. bumping version numbers. Sometimes to even speed things along I'll be ok with updating documentation myself, however in this case there's no need thanks to @saschazar21 :).

Did I give you npm publish access @jarodtaylor? Happy for you to take complete ownership of this package.

**Comment by gijswijs** [comment]
I agree with @jarodtaylor that this PR is good to go. This should result in a minor version bump. I don't have npm publish acces (yet) but I'm going to merge it anyway. Will check with @totocaster if I can get npm access.

**Comment by totocaster** [comment]
@gijswijs, sure DM me your npmjs.org username. It can't find you by `gijswijs`.

**Pull request merged**
